In [1]:
import pandas as pd
import numpy as np

In [30]:
data = pd.read_csv("../data/bankloan.csv")

cols = ["A1","A16"]
X = data.iloc[: , :-1]
y = data.iloc[: , -1]
y

0      1
1      1
2      1
3      1
4      1
      ..
685    0
686    0
687    0
688    0
689    0
Name: A16, Length: 690, dtype: int64

In [39]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

X = X.apply(le.fit_transform)

X

     A1   A2   A3  A4  A5  A6  A7   A8  A9  A10  A11  A12  A13  A14  A15
0     1  157    0   1   0  12   7   30   1    1    1    0    0   69    0
1     0  329   93   1   0  10   3   65   1    1    6    0    0   12  119
2     0   90   16   1   0  10   3   36   1    0    0    0    0   97  140
3     1  126   46   1   0  12   7   73   1    1    5    1    0   32    3
4     1   44  109   1   0  12   7   41   1    0    0    0    2   38    0
..   ..  ...  ...  ..  ..  ..  ..  ...  ..  ...  ...  ...  ...  ...  ...
685   1   53  152   2   2   4   3   30   0    0    0    0    0   91    0
686   0   72   25   1   0   1   7   46   0    1    2    1    0   68  106
687   0   98  186   2   2   5   2   46   0    1    1    1    0   68    1
688   1   21    7   1   0   0   7    1   0    0    0    0    0   97  134
689   1  198   80   1   0   1   3  108   0    0    0    1    0    1    0

[690 rows x 15 columns]

In [41]:
from sklearn.model_selection import train_test_split

# split train and test
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 0)

14     1
586    1
140    1
492    1
350    0
      ..
638    0
479    0
454    0
334    0
474    0
Name: A16, Length: 138, dtype: int64